application: bold-landing-842
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: .*  # This regex directs all routes to main.app
  script: main.app
